### ISSUE TITLE
deploye.zip is empty

### ISSUE THREAD

**Issue by tahseen2k8** [Lightstreamer/Lightstreamer-example-HelloWorld-adapter-php#1]
hi i am new and going to start working on lightstremer  a very powerfull server for real time data
i am trying to use php adapters for learning purpose accourding the tutorial i have to dwonload the deploye.zip and from inside the folder there is a folder Deployment_LS inside another folder PHPHelloWorld . inside this folder there is only a xml file i think there should be some other files like in java adapter . kindly confirm me what i have to do 
https://github.com/Weswit/Lightstreamer-example-HelloWorld-adapter-php/releases

**Comment by gfinocchiaro** [comment]
Hi,

the PHPHelloWorld example comprises two separated components:
- Proxy Adapter configuration files
- Remote Adapter PHP scripts

As explained in the tutorial, you first need to "plug" the Proxy Adapter into the Lightstreamer Server installation, by copying into the adapters directory the PHPHelloWorld folder you have found in deploy.zip file. The Proxy Adapter "talks" with the Remote Adapter over TCP/IP.
Then you have to setup the Remote Adapter, downloading the source code and copying them into a specific folder of the files system.
Once done, launch the Lightstreamer Server and wait for completion of startup.
Finally, you can run the Remote Adapter, by executing the command:

`php helloworld.php`

from the directory you have deployed the source code.

Hope this helps!
Let us know for any further assistance.

Regards,
Gianluca

**Comment by tahseen2k8** [comment]
hey
thanks for quick reply these two folders i have download from git if you
extract you can clearly see that  in deploy.zip contain two folders and
these two folders only contain a single file in tutorial they said that i
have to copy on folder and place it inside the adopter folder of light
streamer .

now can you please categorize
- Proxy Adapter configuration file
- Remote Adapter PHP scripts

and tell me the which files are related to proxy adapter and Remote adapter
it will be a very helpfull for me if you tell me the whole process in steps
with the file conventions.

thanks in advance and really appreciate your work...

regards,

tahseen

**Comment by gfinocchiaro** [comment]
Hi,

deploy.zip file contains only the Proxy Adapter configuration files.
Just for the sake of simplicity, consider the LS_Deployment folder and deploy its content into adapters folder, to get the following directory structure under the lightstreamer installation folder:

[lightstreamer_installation_dir]/adapters/PHPHelloWorld

Such dir should contains only the adapters.xml file.

The Remote Adapter files, instead, are contained  in https://github.com/Weswit/Lightstreamer-example-HelloWorld-adapter-php/archive/v1.0.zip file

Could you please tell me what is not clear in the "Install" section of the tutorial?

Thanks.
Gianluca

**Comment by tahseen2k8** [comment]
hi
Gianluca thanks for reply i got your point  one last thing kindly tell me
the where i have to place remote adapter files..

because when i place it inside the pages folder it doesn't  work and when i
paste it inside my xampp htdocs folder and hit the php helloworld.php file
it shows me this error.

Warning: require(./Thread.php): failed to open stream: No such file or
directory

many thanks for help me.
regards,

**Comment by gfinocchiaro** [comment]
Hi,

remote adapter files are independent of any Lightstreamer installation, they only require a proper PHP installation (and required external library like thread support), as detailed in the tutorial. So you need to unzip the source code wherever you want in your file system. Remember that this is not a php web application, but a php command line application.

Please, feel free to get back us to me if you need more help.
Regards,
Gianluca

**Comment by tahseen2k8** [comment]
Hi,

thanks for support _Gianluca i have follow each step as we discussed but
every thing is OK but the pthread extension_
_required ZTS (Zend thread saftey ) currently using windows 7 OS did not
find a way to install zts in windows environment.._

_so i postpone to integrate php remote adopter and trying to implement
node.js hello world example *
*in this what i do ._
_download_\* deploy folder and paste it inside the adopter folder*
_make a directory and install nodejs helloworld example
through package manager *
*download_\* helloworld.js  file from this link
https://github.com/Weswit/Lightstreamer-example-HelloWorld-client-javascript
run light streamer server *
_then  from my remote adopter directory execute the helloworld.js file as
mentioned in tutorial *
*but it throwing error . I cant figure out what and where i am doing wrong
please help *
*as you helped me before..._

_very warm thanks in advance.._

**Comment by gfinocchiaro** [comment]
Hi,

could you please describe what kind of problem are you experiencing with PHP installation? Have you tried to install the one linked in the tutorial? It has been successfully tested in Windows 7 and 8.
Anyway, please submit issues relative to node adapter example [here](https://github.com/Weswit/Lightstreamer-example-HelloWorld-adapter-node/issues), where you should find other similar issues.
